/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wz.testtask.estore.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.wz.testtask.estore.model.Purchase;
import com.wz.testtask.estore.model.PurchaseModel;
import com.wz.testtask.estore.model.PurchaseSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Purchase service. Represents a row in the &quot;ESTORE_Purchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PurchaseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseImpl}.
 * </p>
 *
 * @author wz
 * @see PurchaseImpl
 * @generated
 */
@JSON(strict = true)
public class PurchaseModelImpl
	extends BaseModelImpl<Purchase> implements PurchaseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a purchase model instance should use the <code>Purchase</code> interface instead.
	 */
	public static final String TABLE_NAME = "ESTORE_Purchase";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"purchaseId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"deviceId", Types.BIGINT}, {"purchasedDate", Types.TIMESTAMP},
		{"count", Types.INTEGER}, {"purchaseTypeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("purchaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deviceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchasedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("count", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("purchaseTypeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ESTORE_Purchase (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,purchaseId LONG not null primary key,groupId LONG,companyId LONG,employeeId LONG,deviceId LONG,purchasedDate DATE null,count INTEGER,purchaseTypeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ESTORE_Purchase";

	public static final String ORDER_BY_JPQL =
		" ORDER BY purchase.purchasedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ESTORE_Purchase.purchasedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEVICEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PURCHASEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Purchase toModel(PurchaseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Purchase model = new PurchaseImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setPurchaseId(soapModel.getPurchaseId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setDeviceId(soapModel.getDeviceId());
		model.setPurchasedDate(soapModel.getPurchasedDate());
		model.setCount(soapModel.getCount());
		model.setPurchaseTypeId(soapModel.getPurchaseTypeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Purchase> toModels(PurchaseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Purchase> models = new ArrayList<Purchase>(soapModels.length);

		for (PurchaseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PurchaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _purchaseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPurchaseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _purchaseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Purchase.class;
	}

	@Override
	public String getModelClassName() {
		return Purchase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Purchase)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Purchase, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Purchase, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Purchase)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Purchase, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Purchase, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Purchase, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Purchase, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Purchase, Object>>();
		Map<String, BiConsumer<Purchase, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Purchase, ?>>();

		attributeGetterFunctions.put("mvccVersion", Purchase::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<Purchase, Long>)Purchase::setMvccVersion);
		attributeGetterFunctions.put("uuid", Purchase::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Purchase, String>)Purchase::setUuid);
		attributeGetterFunctions.put("purchaseId", Purchase::getPurchaseId);
		attributeSetterBiConsumers.put(
			"purchaseId", (BiConsumer<Purchase, Long>)Purchase::setPurchaseId);
		attributeGetterFunctions.put("groupId", Purchase::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Purchase, Long>)Purchase::setGroupId);
		attributeGetterFunctions.put("companyId", Purchase::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Purchase, Long>)Purchase::setCompanyId);
		attributeGetterFunctions.put("employeeId", Purchase::getEmployeeId);
		attributeSetterBiConsumers.put(
			"employeeId", (BiConsumer<Purchase, Long>)Purchase::setEmployeeId);
		attributeGetterFunctions.put("deviceId", Purchase::getDeviceId);
		attributeSetterBiConsumers.put(
			"deviceId", (BiConsumer<Purchase, Long>)Purchase::setDeviceId);
		attributeGetterFunctions.put(
			"purchasedDate", Purchase::getPurchasedDate);
		attributeSetterBiConsumers.put(
			"purchasedDate",
			(BiConsumer<Purchase, Date>)Purchase::setPurchasedDate);
		attributeGetterFunctions.put("count", Purchase::getCount);
		attributeSetterBiConsumers.put(
			"count", (BiConsumer<Purchase, Integer>)Purchase::setCount);
		attributeGetterFunctions.put(
			"purchaseTypeId", Purchase::getPurchaseTypeId);
		attributeSetterBiConsumers.put(
			"purchaseTypeId",
			(BiConsumer<Purchase, Long>)Purchase::setPurchaseTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPurchaseId() {
		return _purchaseId;
	}

	@Override
	public void setPurchaseId(long purchaseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseId = purchaseId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getDeviceId() {
		return _deviceId;
	}

	@Override
	public void setDeviceId(long deviceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deviceId = deviceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDeviceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("deviceId"));
	}

	@JSON
	@Override
	public Date getPurchasedDate() {
		return _purchasedDate;
	}

	@Override
	public void setPurchasedDate(Date purchasedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchasedDate = purchasedDate;
	}

	@JSON
	@Override
	public int getCount() {
		return _count;
	}

	@Override
	public void setCount(int count) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_count = count;
	}

	@JSON
	@Override
	public long getPurchaseTypeId() {
		return _purchaseTypeId;
	}

	@Override
	public void setPurchaseTypeId(long purchaseTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseTypeId = purchaseTypeId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Purchase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Purchase toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Purchase>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PurchaseImpl purchaseImpl = new PurchaseImpl();

		purchaseImpl.setMvccVersion(getMvccVersion());
		purchaseImpl.setUuid(getUuid());
		purchaseImpl.setPurchaseId(getPurchaseId());
		purchaseImpl.setGroupId(getGroupId());
		purchaseImpl.setCompanyId(getCompanyId());
		purchaseImpl.setEmployeeId(getEmployeeId());
		purchaseImpl.setDeviceId(getDeviceId());
		purchaseImpl.setPurchasedDate(getPurchasedDate());
		purchaseImpl.setCount(getCount());
		purchaseImpl.setPurchaseTypeId(getPurchaseTypeId());

		purchaseImpl.resetOriginalValues();

		return purchaseImpl;
	}

	@Override
	public int compareTo(Purchase purchase) {
		int value = 0;

		value = DateUtil.compareTo(
			getPurchasedDate(), purchase.getPurchasedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Purchase)) {
			return false;
		}

		Purchase purchase = (Purchase)object;

		long primaryKey = purchase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Purchase> toCacheModel() {
		PurchaseCacheModel purchaseCacheModel = new PurchaseCacheModel();

		purchaseCacheModel.mvccVersion = getMvccVersion();

		purchaseCacheModel.uuid = getUuid();

		String uuid = purchaseCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			purchaseCacheModel.uuid = null;
		}

		purchaseCacheModel.purchaseId = getPurchaseId();

		purchaseCacheModel.groupId = getGroupId();

		purchaseCacheModel.companyId = getCompanyId();

		purchaseCacheModel.employeeId = getEmployeeId();

		purchaseCacheModel.deviceId = getDeviceId();

		Date purchasedDate = getPurchasedDate();

		if (purchasedDate != null) {
			purchaseCacheModel.purchasedDate = purchasedDate.getTime();
		}
		else {
			purchaseCacheModel.purchasedDate = Long.MIN_VALUE;
		}

		purchaseCacheModel.count = getCount();

		purchaseCacheModel.purchaseTypeId = getPurchaseTypeId();

		return purchaseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Purchase)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Purchase)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Purchase>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Purchase.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _purchaseId;
	private long _groupId;
	private long _companyId;
	private long _employeeId;
	private long _deviceId;
	private Date _purchasedDate;
	private int _count;
	private long _purchaseTypeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Purchase, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Purchase)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("purchaseId", _purchaseId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("deviceId", _deviceId);
		_columnOriginalValues.put("purchasedDate", _purchasedDate);
		_columnOriginalValues.put("count", _count);
		_columnOriginalValues.put("purchaseTypeId", _purchaseTypeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("purchaseId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("employeeId", 32L);

		columnBitmasks.put("deviceId", 64L);

		columnBitmasks.put("purchasedDate", 128L);

		columnBitmasks.put("count", 256L);

		columnBitmasks.put("purchaseTypeId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Purchase _escapedModel;

}