/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wz.testtask.estore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DeviceType service. Represents a row in the &quot;ESTORE_DeviceType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.wz.testtask.estore.model.impl.DeviceTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.wz.testtask.estore.model.impl.DeviceTypeImpl</code>.
 * </p>
 *
 * @author wz
 * @see DeviceType
 * @generated
 */
@ProviderType
public interface DeviceTypeModel
	extends BaseModel<DeviceType>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device type model instance should use the {@link DeviceType} interface instead.
	 */

	/**
	 * Returns the primary key of this device type.
	 *
	 * @return the primary key of this device type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this device type.
	 *
	 * @param primaryKey the primary key of this device type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this device type.
	 *
	 * @return the mvcc version of this device type
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this device type.
	 *
	 * @param mvccVersion the mvcc version of this device type
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this device type.
	 *
	 * @return the uuid of this device type
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this device type.
	 *
	 * @param uuid the uuid of this device type
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the device type ID of this device type.
	 *
	 * @return the device type ID of this device type
	 */
	public long getDeviceTypeId();

	/**
	 * Sets the device type ID of this device type.
	 *
	 * @param deviceTypeId the device type ID of this device type
	 */
	public void setDeviceTypeId(long deviceTypeId);

	/**
	 * Returns the group ID of this device type.
	 *
	 * @return the group ID of this device type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this device type.
	 *
	 * @param groupId the group ID of this device type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this device type.
	 *
	 * @return the company ID of this device type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this device type.
	 *
	 * @param companyId the company ID of this device type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this device type.
	 *
	 * @return the name of this device type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this device type.
	 *
	 * @param name the name of this device type
	 */
	public void setName(String name);

}