/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wz.testtask.estore.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeWithSummary service. Represents a row in the &quot;ESTORE_EmployeeWithSummary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.wz.testtask.estore.model.impl.EmployeeWithSummaryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.wz.testtask.estore.model.impl.EmployeeWithSummaryImpl</code>.
 * </p>
 *
 * @author wz
 * @see EmployeeWithSummary
 * @generated
 */
@ProviderType
public interface EmployeeWithSummaryModel
	extends BaseModel<EmployeeWithSummary>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee with summary model instance should use the {@link EmployeeWithSummary} interface instead.
	 */

	/**
	 * Returns the primary key of this employee with summary.
	 *
	 * @return the primary key of this employee with summary
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee with summary.
	 *
	 * @param primaryKey the primary key of this employee with summary
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this employee with summary.
	 *
	 * @return the mvcc version of this employee with summary
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this employee with summary.
	 *
	 * @param mvccVersion the mvcc version of this employee with summary
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the employee ID of this employee with summary.
	 *
	 * @return the employee ID of this employee with summary
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee with summary.
	 *
	 * @param employeeId the employee ID of this employee with summary
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the employee full name of this employee with summary.
	 *
	 * @return the employee full name of this employee with summary
	 */
	@AutoEscape
	public String getEmployeeFullName();

	/**
	 * Sets the employee full name of this employee with summary.
	 *
	 * @param employeeFullName the employee full name of this employee with summary
	 */
	public void setEmployeeFullName(String employeeFullName);

	/**
	 * Returns the device count of this employee with summary.
	 *
	 * @return the device count of this employee with summary
	 */
	public int getDeviceCount();

	/**
	 * Sets the device count of this employee with summary.
	 *
	 * @param deviceCount the device count of this employee with summary
	 */
	public void setDeviceCount(int deviceCount);

	/**
	 * Returns the sold devices on of this employee with summary.
	 *
	 * @return the sold devices on of this employee with summary
	 */
	public long getSoldDevicesOn();

	/**
	 * Sets the sold devices on of this employee with summary.
	 *
	 * @param soldDevicesOn the sold devices on of this employee with summary
	 */
	public void setSoldDevicesOn(long soldDevicesOn);

}